GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "otsikko",
    "author": "kirjoittaja",
    "url": "osoite",
    "likes": 3    
}

###

DELETE http://localhost:3003/api/blogs/5b145b564a9d7967653c7ab

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "käyttäjänimi 3",
  "name": "nimi",
  "password": "salasana",
  "adult": true
}