GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "otsikko",
    "author": "kirjoittaja",
    "url": "osoite",
    "likes": 3,
    "userId": "5b16868b0568ee2caad9b98f"    
}

###

DELETE http://localhost:3003/api/blogs/5b145b564a9d7967653c7ab

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "kässssssss",
  "name": "nimi",
  "password": "salasana"
}